version: '2.2'

services:
  app:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  static:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - app
    links:
      - app
  mongo:
    image: mongo
    ports:
    - "27018:27017"
    volumes:
    - mongo:/data/db
volumes:
  mongo: