// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import cpfCnpj "github.com/rkorpalski/validatorCpfCnpj/backend/pkg/cpfCnpj"
import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Save provides a mock function with given fields: _a0
func (_m *Service) Save(_a0 *cpfCnpj.CpfCnpj) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cpfCnpj.CpfCnpj) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Validate provides a mock function with given fields: documentNumber
func (_m *Service) Validate(documentNumber string) (bool, error) {
	ret := _m.Called(documentNumber)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(documentNumber)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(documentNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
